spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/spring_security_exam
#    username: user
#    password: 11111

    url: jdbc:mysql://localhost:3306/spring_security_exam
    username: root
    password: 11111

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    user:
      password: "{noop}1111"
      name: user

    authentication:
      api:
        login-url: "/accounts/login"